apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Let's Encrypt staging server (for testing)
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    
    # Email for certificate expiration notifications
    email: devops@fastfood.com
    
    # Secret to store ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    
    # HTTP-01 challenge solver
    solvers:
      # HTTP-01 solver for most domains
      - http01:
          ingress:
            class: nginx
        selector:
          dnsZones:
            - "fastfood.local"
            - "fastfood-dev.local"
      
      # DNS-01 solver for wildcard certificates (optional)
      # Uncomment and configure if using DNS-01
      # - dns01:
      #     cloudflare:
      #       email: your-email@example.com
      #       apiTokenSecretRef:
      #         name: cloudflare-api-token
      #         key: api-token
      #   selector:
      #     dnsZones:
      #       - "*.fastfood.com"
